CPPFLAGS = -std=c++14 -Wall

all:
	g++ ${CPPFLAGS} main.cpp -o tama
	./tama < example1.txt > out.txt
	vim out.txt

example2:	
	g++ ${CPPFLAGS} main.cpp -o tama
	./tama < example2.txt > out.txt
	vim out.txt

example3:	
	g++ ${CPPFLAGS} main.cpp -o tama
	./tama < example3.txt > out.txt
	vim out.txt
